/*
 * Copyright (c) 2026 Pawan Osman <https://github.com/PawanOsman>
 *
 * This file is part of OpenCursor — AI coding agent chat inside VS Code.
 * https://github.com/PawanOsman/OpenCursor
 *
 * Licensed under the MIT License. See LICENSE file in the project root.
 */

// Generated by scripts/generate-runtime-manifest.cjs from pnpm-lock.yaml.
export const runtimeManifest = {
  "version": 1,
  "roots": {
    "@huggingface/transformers": "@huggingface/transformers@4.2.0",
    "@huggingface/hub": "@huggingface/hub@2.13.2",
    "onnxruntime-node": "onnxruntime-node@1.27.0",
    "sharp": "sharp@0.35.2",
    "pdf-parse": "pdf-parse@2.4.5",
    "@lydell/node-pty": "@lydell/node-pty@1.2.0-beta.15",
    "playwright-core": "playwright-core@1.63.0"
  },
  "packages": {
    "@emnapi/runtime@1.11.1": {
      "name": "@emnapi/runtime",
      "version": "1.11.1",
      "integrity": "sha512-vgj7R3y3Wgx24IQaGPA/R6YFXLHVMOZ0uVEyIQPaWs+rd1AzfEMXlAC22FYwO1XkKR6NPsq7mUandH8oIRdZFw==",
      "tarball": "https://registry.npmjs.org/@emnapi/runtime/-/runtime-1.11.1.tgz",
      "dependencies": {
        "tslib": "tslib@2.8.1"
      },
      "optionalDependencies": {}
    },
    "@huggingface/blake3-jit@0.0.2": {
      "name": "@huggingface/blake3-jit",
      "version": "0.0.2",
      "integrity": "sha512-Bq7B5qabyjrJfhBsl85Jd2QBtf+HzRD7h7A9GfN2lzrrsABhOa5evVPgzoCTxR7Ub0QFj7YDK1YkYRWBU25+2w==",
      "tarball": "https://registry.npmjs.org/@huggingface/blake3-jit/-/blake3-jit-0.0.2.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@huggingface/hub@2.13.2": {
      "name": "@huggingface/hub",
      "version": "2.13.2",
      "integrity": "sha512-I1Pbn9UcBHCt0M/SbZkKzYr3JVnbJp4YIFv74eVRH2Y22yT9Jpm6DtfM74tcjNLbC7SyFZ433znUw0szdFd4Fg==",
      "tarball": "https://registry.npmjs.org/@huggingface/hub/-/hub-2.13.2.tgz",
      "dependencies": {
        "@huggingface/tasks": "@huggingface/tasks@0.21.17",
        "@huggingface/xetchunk-wasm": "@huggingface/xetchunk-wasm@0.1.0"
      },
      "optionalDependencies": {
        "cli-progress": "cli-progress@3.12.0"
      }
    },
    "@huggingface/jinja@0.5.9": {
      "name": "@huggingface/jinja",
      "version": "0.5.9",
      "integrity": "sha512-uWTG+l3VJRsl7EXxYizuL3P+cCPoc3cRqbWWRcQN0FhejRfbdq0RNhCmbY/YDtnTcz9icdLYuLDjsnz4d8JMuw==",
      "tarball": "https://registry.npmjs.org/@huggingface/jinja/-/jinja-0.5.9.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@huggingface/tasks@0.21.17": {
      "name": "@huggingface/tasks",
      "version": "0.21.17",
      "integrity": "sha512-vdhQXFBb8hFm4U4KLGDT5a3C1JzSUU16Zoh4DJ1KDL3cdnIrUt+tIX+P1IxqZoXXx55PUQTJBu8iHH2HXtnBGg==",
      "tarball": "https://registry.npmjs.org/@huggingface/tasks/-/tasks-0.21.17.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@huggingface/tokenizers@0.1.3": {
      "name": "@huggingface/tokenizers",
      "version": "0.1.3",
      "integrity": "sha512-8rF/RRT10u+kn7YuUbUg0OF30K8rjTc78aHpxT+qJ1uWSqxT1MHi8+9ltwYfkFYJzT/oS+qw3JVfHtNMGAdqyA==",
      "tarball": "https://registry.npmjs.org/@huggingface/tokenizers/-/tokenizers-0.1.3.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@huggingface/transformers@4.2.0": {
      "name": "@huggingface/transformers",
      "version": "4.2.0",
      "integrity": "sha512-8BRCoBMH0XsWaEIamuR0LrJGAfftgHAfb2Vrffy0VKlSAE/MnUJ5/h/zTfEP3fDIft+nk7TqB8xXEyABGitBjQ==",
      "tarball": "https://registry.npmjs.org/@huggingface/transformers/-/transformers-4.2.0.tgz",
      "dependencies": {
        "@huggingface/jinja": "@huggingface/jinja@0.5.9",
        "@huggingface/tokenizers": "@huggingface/tokenizers@0.1.3",
        "onnxruntime-node": "onnxruntime-node@1.24.3",
        "sharp": "sharp@0.34.5",
        "onnxruntime-common": "onnxruntime-common@1.24.3"
      },
      "optionalDependencies": {}
    },
    "@huggingface/xetchunk-wasm@0.1.0": {
      "name": "@huggingface/xetchunk-wasm",
      "version": "0.1.0",
      "integrity": "sha512-wWpp2qwPgf9kv1KLJjcDUk/OrpDOsFoQ3Qpz0U5LGn20csoymBf8eneOv6wm/GzPBzlWac1OYiR0aa1vT6aM2Q==",
      "tarball": "https://registry.npmjs.org/@huggingface/xetchunk-wasm/-/xetchunk-wasm-0.1.0.tgz",
      "dependencies": {
        "@huggingface/blake3-jit": "@huggingface/blake3-jit@0.0.2",
        "gearhash-jit": "gearhash-jit@1.0.2"
      },
      "optionalDependencies": {}
    },
    "@img/colour@1.1.0": {
      "name": "@img/colour",
      "version": "1.1.0",
      "integrity": "sha512-Td76q7j57o/tLVdgS746cYARfSyxk8iEfRxewL9h4OMzYhbW4TAcppl0mT4eyqXddh6L/jwoM75mo7ixa/pCeQ==",
      "tarball": "https://registry.npmjs.org/@img/colour/-/colour-1.1.0.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-darwin-arm64@0.34.5": {
      "name": "@img/sharp-darwin-arm64",
      "version": "0.34.5",
      "integrity": "sha512-imtQ3WMJXbMY4fxb/Ndp6HBTNVtWCUI0WdobyheGf5+ad6xX8VIDO8u2xE4qc/fr08CKG/7dDseFtn6M6g/r3w==",
      "tarball": "https://registry.npmjs.org/@img/sharp-darwin-arm64/-/sharp-darwin-arm64-0.34.5.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-darwin-arm64": "@img/sharp-libvips-darwin-arm64@1.2.4"
      }
    },
    "@img/sharp-darwin-arm64@0.35.2": {
      "name": "@img/sharp-darwin-arm64",
      "version": "0.35.2",
      "integrity": "sha512-eEieHsMksAW4IiO5NzauESRl2D2qz3J/kwUxUrSfV06A93eEaRfMpHXyUb1mAqrR7i8U9A0GRqE9pjn6u1Jjpg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-darwin-arm64/-/sharp-darwin-arm64-0.35.2.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-darwin-arm64": "@img/sharp-libvips-darwin-arm64@1.3.1"
      }
    },
    "@img/sharp-darwin-x64@0.34.5": {
      "name": "@img/sharp-darwin-x64",
      "version": "0.34.5",
      "integrity": "sha512-YNEFAF/4KQ/PeW0N+r+aVVsoIY0/qxxikF2SWdp+NRkmMB7y9LBZAVqQ4yhGCm/H3H270OSykqmQMKLBhBJDEw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-darwin-x64/-/sharp-darwin-x64-0.34.5.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-darwin-x64": "@img/sharp-libvips-darwin-x64@1.2.4"
      }
    },
    "@img/sharp-darwin-x64@0.35.2": {
      "name": "@img/sharp-darwin-x64",
      "version": "0.35.2",
      "integrity": "sha512-BaktuGPCeHJMARpodR8jK4uKiZrPAy9WrfQW0sdI37clracq8Bp01AYS3SZgi5FS/y5twa9t4+LIuuxQjqRrWw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-darwin-x64/-/sharp-darwin-x64-0.35.2.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-darwin-x64": "@img/sharp-libvips-darwin-x64@1.3.1"
      }
    },
    "@img/sharp-freebsd-wasm32@0.35.2": {
      "name": "@img/sharp-freebsd-wasm32",
      "version": "0.35.2",
      "integrity": "sha512-YoAxdnd8hPUkvLHd3bWY+YA8nw3xM/RyRopYucNsWHVSan8NLVM3X2volsfoRDcXdUJPg6tXahSd7HXPK7lRnw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-freebsd-wasm32/-/sharp-freebsd-wasm32-0.35.2.tgz",
      "os": [
        "freebsd"
      ],
      "dependencies": {
        "@img/sharp-wasm32": "@img/sharp-wasm32@0.35.2"
      },
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-darwin-arm64@1.2.4": {
      "name": "@img/sharp-libvips-darwin-arm64",
      "version": "1.2.4",
      "integrity": "sha512-zqjjo7RatFfFoP0MkQ51jfuFZBnVE2pRiaydKJ1G/rHZvnsrHAOcQALIi9sA5co5xenQdTugCvtb1cuf78Vf4g==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-darwin-arm64/-/sharp-libvips-darwin-arm64-1.2.4.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-darwin-arm64@1.3.1": {
      "name": "@img/sharp-libvips-darwin-arm64",
      "version": "1.3.1",
      "integrity": "sha512-4V/M3roRMTYjiwZY9IOVQOE8OyeCxFAkYmyZDrZl51uOKjibm3oeEJ4WAmLxutAfzFbC9jqUiPs2gbnGflH+7g==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-darwin-arm64/-/sharp-libvips-darwin-arm64-1.3.1.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-darwin-x64@1.2.4": {
      "name": "@img/sharp-libvips-darwin-x64",
      "version": "1.2.4",
      "integrity": "sha512-1IOd5xfVhlGwX+zXv2N93k0yMONvUlANylbJw1eTah8K/Jtpi15KC+WSiaX/nBmbm2HxRM1gZ0nSdjSsrZbGKg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-darwin-x64/-/sharp-libvips-darwin-x64-1.2.4.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-darwin-x64@1.3.1": {
      "name": "@img/sharp-libvips-darwin-x64",
      "version": "1.3.1",
      "integrity": "sha512-c0/DxItpJv2+dGhgycJBBgotdqruGYDvA79drdh0MD1dFpy7JzJ/PlXwi1H4rFf0eTy8tgbI91aHDnZIceY3jQ==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-darwin-x64/-/sharp-libvips-darwin-x64-1.3.1.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-arm@1.2.4": {
      "name": "@img/sharp-libvips-linux-arm",
      "version": "1.2.4",
      "integrity": "sha512-bFI7xcKFELdiNCVov8e44Ia4u2byA+l3XtsAj+Q8tfCwO6BQ8iDojYdvoPMqsKDkuoOo+X6HZA0s0q11ANMQ8A==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-arm/-/sharp-libvips-linux-arm-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-arm@1.3.1": {
      "name": "@img/sharp-libvips-linux-arm",
      "version": "1.3.1",
      "integrity": "sha512-aGGy9aWzXgHBG7HNyQPWorZthlp7+x6fDRoPAQbGO3ThcttuTyKIx3NuSHb6zb4gBNq6/yNn9f1cy9nFKS/Vmg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-arm/-/sharp-libvips-linux-arm-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-arm64@1.2.4": {
      "name": "@img/sharp-libvips-linux-arm64",
      "version": "1.2.4",
      "integrity": "sha512-excjX8DfsIcJ10x1Kzr4RcWe1edC9PquDRRPx3YVCvQv+U5p7Yin2s32ftzikXojb1PIFc/9Mt28/y+iRklkrw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-arm64/-/sharp-libvips-linux-arm64-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-arm64@1.3.1": {
      "name": "@img/sharp-libvips-linux-arm64",
      "version": "1.3.1",
      "integrity": "sha512-JznefmcK9j1JKPz8AkQDh89kjojubyfOasWBPKfzMIhPwsgDy9evpE/naJTXXXmghS1iFwR8u/kTwh/I2/+GCw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-arm64/-/sharp-libvips-linux-arm64-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-ppc64@1.2.4": {
      "name": "@img/sharp-libvips-linux-ppc64",
      "version": "1.2.4",
      "integrity": "sha512-FMuvGijLDYG6lW+b/UvyilUWu5Ayu+3r2d1S8notiGCIyYU/76eig1UfMmkZ7vwgOrzKzlQbFSuQfgm7GYUPpA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-ppc64/-/sharp-libvips-linux-ppc64-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "ppc64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-ppc64@1.3.1": {
      "name": "@img/sharp-libvips-linux-ppc64",
      "version": "1.3.1",
      "integrity": "sha512-1EkwGNCZk6iWNCMWqrvdJ+r1j0PT1zIz60CNPhYnJlK/zyeWqlsPZIe+ocBVqPF8k/Ssee/NCk+tE9Ryrko6ng==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-ppc64/-/sharp-libvips-linux-ppc64-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "ppc64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-riscv64@1.2.4": {
      "name": "@img/sharp-libvips-linux-riscv64",
      "version": "1.2.4",
      "integrity": "sha512-oVDbcR4zUC0ce82teubSm+x6ETixtKZBh/qbREIOcI3cULzDyb18Sr/Wcyx7NRQeQzOiHTNbZFF1UwPS2scyGA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-riscv64/-/sharp-libvips-linux-riscv64-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "riscv64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-riscv64@1.3.1": {
      "name": "@img/sharp-libvips-linux-riscv64",
      "version": "1.3.1",
      "integrity": "sha512-Ilays+w2bXdnxzxtQdmXR62u8o8GYa3eL4+Gr+1KiE4xperMZUslRaVPJwwPkzlHEjGfXAfRVAa/7CYCtSqsBw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-riscv64/-/sharp-libvips-linux-riscv64-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "riscv64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-s390x@1.2.4": {
      "name": "@img/sharp-libvips-linux-s390x",
      "version": "1.2.4",
      "integrity": "sha512-qmp9VrzgPgMoGZyPvrQHqk02uyjA0/QrTO26Tqk6l4ZV0MPWIW6LTkqOIov+J1yEu7MbFQaDpwdwJKhbJvuRxQ==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-s390x/-/sharp-libvips-linux-s390x-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "s390x"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-s390x@1.3.1": {
      "name": "@img/sharp-libvips-linux-s390x",
      "version": "1.3.1",
      "integrity": "sha512-VfBwVHQTbRoj4XlpA/KLZ7ltgMpz+4WSejFzQ+GnoImjo1PtEJ59QB2qR1xQEeRPYIkNrPIm2L4cICMvz4C2ew==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-s390x/-/sharp-libvips-linux-s390x-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "s390x"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-x64@1.2.4": {
      "name": "@img/sharp-libvips-linux-x64",
      "version": "1.2.4",
      "integrity": "sha512-tJxiiLsmHc9Ax1bz3oaOYBURTXGIRDODBqhveVHonrHJ9/+k89qbLl0bcJns+e4t4rvaNBxaEZsFtSfAdquPrw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-x64/-/sharp-libvips-linux-x64-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linux-x64@1.3.1": {
      "name": "@img/sharp-libvips-linux-x64",
      "version": "1.3.1",
      "integrity": "sha512-+c8ukgwU62DS54nCAjw7keOfHUkmr0B5QHEdcOqRnodF/MNXJbVI8Eopoj4B/0H8Asr65I+A4Amrn7a85/md6A==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linux-x64/-/sharp-libvips-linux-x64-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linuxmusl-arm64@1.2.4": {
      "name": "@img/sharp-libvips-linuxmusl-arm64",
      "version": "1.2.4",
      "integrity": "sha512-FVQHuwx1IIuNow9QAbYUzJ+En8KcVm9Lk5+uGUQJHaZmMECZmOlix9HnH7n1TRkXMS0pGxIJokIVB9SuqZGGXw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linuxmusl-arm64/-/sharp-libvips-linuxmusl-arm64-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linuxmusl-arm64@1.3.1": {
      "name": "@img/sharp-libvips-linuxmusl-arm64",
      "version": "1.3.1",
      "integrity": "sha512-qlKb/pwbkAi1WMsJrYHk7CuDrd12s27U2QnRhFYUoJNrRCmkosMTttuRFat/DDB3IlDm5qE1TJgZ4JDnHX8Ldw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linuxmusl-arm64/-/sharp-libvips-linuxmusl-arm64-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linuxmusl-x64@1.2.4": {
      "name": "@img/sharp-libvips-linuxmusl-x64",
      "version": "1.2.4",
      "integrity": "sha512-+LpyBk7L44ZIXwz/VYfglaX/okxezESc6UxDSoyo2Ks6Jxc4Y7sGjpgU9s4PMgqgjj1gZCylTieNamqA1MF7Dg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linuxmusl-x64/-/sharp-libvips-linuxmusl-x64-1.2.4.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-libvips-linuxmusl-x64@1.3.1": {
      "name": "@img/sharp-libvips-linuxmusl-x64",
      "version": "1.3.1",
      "integrity": "sha512-yO21HwoUVLN8Qa+/SBjQLMYwBWAVJjeGPNe+hc0OUeMeifEtJqu5a1c4HayE1nNpDih9y3/KkoltfkDodmKAlg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-libvips-linuxmusl-x64/-/sharp-libvips-linuxmusl-x64-1.3.1.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-linux-arm@0.34.5": {
      "name": "@img/sharp-linux-arm",
      "version": "0.34.5",
      "integrity": "sha512-9dLqsvwtg1uuXBGZKsxem9595+ujv0sJ6Vi8wcTANSFpwV/GONat5eCkzQo/1O6zRIkh0m/8+5BjrRr7jDUSZw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-arm/-/sharp-linux-arm-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-arm": "@img/sharp-libvips-linux-arm@1.2.4"
      }
    },
    "@img/sharp-linux-arm@0.35.2": {
      "name": "@img/sharp-linux-arm",
      "version": "0.35.2",
      "integrity": "sha512-SE4kzF2mepn6z+6E7L6lsV8FzuLL6IPQdyX8ZiwROAG/G8td+hP/m7FsFPwidtrF19gvajuC9l6TxAVcsA4S7A==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-arm/-/sharp-linux-arm-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-arm": "@img/sharp-libvips-linux-arm@1.3.1"
      }
    },
    "@img/sharp-linux-arm64@0.34.5": {
      "name": "@img/sharp-linux-arm64",
      "version": "0.34.5",
      "integrity": "sha512-bKQzaJRY/bkPOXyKx5EVup7qkaojECG6NLYswgktOZjaXecSAeCWiZwwiFf3/Y+O1HrauiE3FVsGxFg8c24rZg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-arm64/-/sharp-linux-arm64-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-arm64": "@img/sharp-libvips-linux-arm64@1.2.4"
      }
    },
    "@img/sharp-linux-arm64@0.35.2": {
      "name": "@img/sharp-linux-arm64",
      "version": "0.35.2",
      "integrity": "sha512-af12Pnd0ZGu2HfP8NayB0kk6eC/lrfbQE6HlR4jD+34wdJ1Vw9TF6TMn6ZvffT+WgqVsl0hRbmNvz2u/23VmwA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-arm64/-/sharp-linux-arm64-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-arm64": "@img/sharp-libvips-linux-arm64@1.3.1"
      }
    },
    "@img/sharp-linux-ppc64@0.34.5": {
      "name": "@img/sharp-linux-ppc64",
      "version": "0.34.5",
      "integrity": "sha512-7zznwNaqW6YtsfrGGDA6BRkISKAAE1Jo0QdpNYXNMHu2+0dTrPflTLNkpc8l7MUP5M16ZJcUvysVWWrMefZquA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-ppc64/-/sharp-linux-ppc64-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "ppc64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-ppc64": "@img/sharp-libvips-linux-ppc64@1.2.4"
      }
    },
    "@img/sharp-linux-ppc64@0.35.2": {
      "name": "@img/sharp-linux-ppc64",
      "version": "0.35.2",
      "integrity": "sha512-hYSBm7zcNtDCozCxQHYZJiu63b/bXsgRZuOxCIBZsStMM9Vap47iFHdbX4kCvQsblPB/k+clhELpdQJHQLSHvg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-ppc64/-/sharp-linux-ppc64-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "ppc64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-ppc64": "@img/sharp-libvips-linux-ppc64@1.3.1"
      }
    },
    "@img/sharp-linux-riscv64@0.34.5": {
      "name": "@img/sharp-linux-riscv64",
      "version": "0.34.5",
      "integrity": "sha512-51gJuLPTKa7piYPaVs8GmByo7/U7/7TZOq+cnXJIHZKavIRHAP77e3N2HEl3dgiqdD/w0yUfiJnII77PuDDFdw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-riscv64/-/sharp-linux-riscv64-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "riscv64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-riscv64": "@img/sharp-libvips-linux-riscv64@1.2.4"
      }
    },
    "@img/sharp-linux-riscv64@0.35.2": {
      "name": "@img/sharp-linux-riscv64",
      "version": "0.35.2",
      "integrity": "sha512-qQt0Kc13+Hoan/Awq/qMSQw3L+RI1NCRPgD5cUJ/1WSSmIoysLOc72jlRM3E0OHN9Yr313jgeQ2T+zW+F03QFA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-riscv64/-/sharp-linux-riscv64-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "riscv64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-riscv64": "@img/sharp-libvips-linux-riscv64@1.3.1"
      }
    },
    "@img/sharp-linux-s390x@0.34.5": {
      "name": "@img/sharp-linux-s390x",
      "version": "0.34.5",
      "integrity": "sha512-nQtCk0PdKfho3eC5MrbQoigJ2gd1CgddUMkabUj+rBevs8tZ2cULOx46E7oyX+04WGfABgIwmMC0VqieTiR4jg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-s390x/-/sharp-linux-s390x-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "s390x"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-s390x": "@img/sharp-libvips-linux-s390x@1.2.4"
      }
    },
    "@img/sharp-linux-s390x@0.35.2": {
      "name": "@img/sharp-linux-s390x",
      "version": "0.35.2",
      "integrity": "sha512-E4fLLfRPzDLlEeDaTzI98OFLcv++WL5ChLLMwPoVd0CIoZQqupBSNbOisPL5am9XsbQ9T84+iiMpUvbFtkunbA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-s390x/-/sharp-linux-s390x-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "s390x"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-s390x": "@img/sharp-libvips-linux-s390x@1.3.1"
      }
    },
    "@img/sharp-linux-x64@0.34.5": {
      "name": "@img/sharp-linux-x64",
      "version": "0.34.5",
      "integrity": "sha512-MEzd8HPKxVxVenwAa+JRPwEC7QFjoPWuS5NZnBt6B3pu7EG2Ge0id1oLHZpPJdn3OQK+BQDiw9zStiHBTJQQQQ==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-x64/-/sharp-linux-x64-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-x64": "@img/sharp-libvips-linux-x64@1.2.4"
      }
    },
    "@img/sharp-linux-x64@0.35.2": {
      "name": "@img/sharp-linux-x64",
      "version": "0.35.2",
      "integrity": "sha512-gi0zFJJRLswfCZmHtJdikXPOc5u7qamSOS3NHedLqLd4W8Q0NqjdBr6TTRIgsfFjqfTsHFgdfvJ9LwqSgcHiAA==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linux-x64/-/sharp-linux-x64-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linux-x64": "@img/sharp-libvips-linux-x64@1.3.1"
      }
    },
    "@img/sharp-linuxmusl-arm64@0.34.5": {
      "name": "@img/sharp-linuxmusl-arm64",
      "version": "0.34.5",
      "integrity": "sha512-fprJR6GtRsMt6Kyfq44IsChVZeGN97gTD331weR1ex1c1rypDEABN6Tm2xa1wE6lYb5DdEnk03NZPqA7Id21yg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linuxmusl-arm64/-/sharp-linuxmusl-arm64-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linuxmusl-arm64": "@img/sharp-libvips-linuxmusl-arm64@1.2.4"
      }
    },
    "@img/sharp-linuxmusl-arm64@0.35.2": {
      "name": "@img/sharp-linuxmusl-arm64",
      "version": "0.35.2",
      "integrity": "sha512-siWbOW1u6HFnFLrp0waKyW7VEf7jYvcDWdrXEFa8AkdAQgEvuu5Fz8/Y70w9EeqAdwDtfU012BhEHHaDqvQNzg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linuxmusl-arm64/-/sharp-linuxmusl-arm64-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linuxmusl-arm64": "@img/sharp-libvips-linuxmusl-arm64@1.3.1"
      }
    },
    "@img/sharp-linuxmusl-x64@0.34.5": {
      "name": "@img/sharp-linuxmusl-x64",
      "version": "0.34.5",
      "integrity": "sha512-Jg8wNT1MUzIvhBFxViqrEhWDGzqymo3sV7z7ZsaWbZNDLXRJZoRGrjulp60YYtV4wfY8VIKcWidjojlLcWrd8Q==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linuxmusl-x64/-/sharp-linuxmusl-x64-0.34.5.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linuxmusl-x64": "@img/sharp-libvips-linuxmusl-x64@1.2.4"
      }
    },
    "@img/sharp-linuxmusl-x64@0.35.2": {
      "name": "@img/sharp-linuxmusl-x64",
      "version": "0.35.2",
      "integrity": "sha512-YBqMMcjDi4QGYiSn4vNOYBhmlC4z5AXqkOUUqI2e0AFA4urNv4ESgOgwNl3K+4etQhha0twXlzeF20bbULm9Yg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-linuxmusl-x64/-/sharp-linuxmusl-x64-0.35.2.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {
        "@img/sharp-libvips-linuxmusl-x64": "@img/sharp-libvips-linuxmusl-x64@1.3.1"
      }
    },
    "@img/sharp-wasm32@0.34.5": {
      "name": "@img/sharp-wasm32",
      "version": "0.34.5",
      "integrity": "sha512-OdWTEiVkY2PHwqkbBI8frFxQQFekHaSSkUIJkwzclWZe64O1X4UlUjqqqLaPbUpMOQk6FBu/HtlGXNblIs0huw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-wasm32/-/sharp-wasm32-0.34.5.tgz",
      "cpu": [
        "wasm32"
      ],
      "dependencies": {
        "@emnapi/runtime": "@emnapi/runtime@1.11.1"
      },
      "optionalDependencies": {}
    },
    "@img/sharp-wasm32@0.35.2": {
      "name": "@img/sharp-wasm32",
      "version": "0.35.2",
      "integrity": "sha512-Mrv4JQNYVQ94xH+jzZ9r+gowleN8mv2FTgKT+PI6bx5C0G8TdNYndu161pg2i7uoBwxy2ImPMHrJOM2LZef7Bw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-wasm32/-/sharp-wasm32-0.35.2.tgz",
      "dependencies": {
        "@emnapi/runtime": "@emnapi/runtime@1.11.1"
      },
      "optionalDependencies": {}
    },
    "@img/sharp-webcontainers-wasm32@0.35.2": {
      "name": "@img/sharp-webcontainers-wasm32",
      "version": "0.35.2",
      "integrity": "sha512-QNV27pxs9wpApEiCfvHM1RDoP1w1+2KrUWWDPEhEwg+latvOrfuhWrHWZKwdSFwU6jh3myjw/yOCRsUIuOft3g==",
      "tarball": "https://registry.npmjs.org/@img/sharp-webcontainers-wasm32/-/sharp-webcontainers-wasm32-0.35.2.tgz",
      "cpu": [
        "wasm32"
      ],
      "dependencies": {
        "@img/sharp-wasm32": "@img/sharp-wasm32@0.35.2"
      },
      "optionalDependencies": {}
    },
    "@img/sharp-win32-arm64@0.34.5": {
      "name": "@img/sharp-win32-arm64",
      "version": "0.34.5",
      "integrity": "sha512-WQ3AgWCWYSb2yt+IG8mnC6Jdk9Whs7O0gxphblsLvdhSpSTtmu69ZG1Gkb6NuvxsNACwiPV6cNSZNzt0KPsw7g==",
      "tarball": "https://registry.npmjs.org/@img/sharp-win32-arm64/-/sharp-win32-arm64-0.34.5.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-win32-arm64@0.35.2": {
      "name": "@img/sharp-win32-arm64",
      "version": "0.35.2",
      "integrity": "sha512-BiVRYc/t6/Vl3e1hBx0hugG4oN9Pydf4fgMSpxTQJmwGUg/YoXTWHiFeRymHfCZzifxu4F4rpk/I67D0LQ20wQ==",
      "tarball": "https://registry.npmjs.org/@img/sharp-win32-arm64/-/sharp-win32-arm64-0.35.2.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-win32-ia32@0.34.5": {
      "name": "@img/sharp-win32-ia32",
      "version": "0.34.5",
      "integrity": "sha512-FV9m/7NmeCmSHDD5j4+4pNI8Cp3aW+JvLoXcTUo0IqyjSfAZJ8dIUmijx1qaJsIiU+Hosw6xM5KijAWRJCSgNg==",
      "tarball": "https://registry.npmjs.org/@img/sharp-win32-ia32/-/sharp-win32-ia32-0.34.5.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "ia32"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-win32-ia32@0.35.2": {
      "name": "@img/sharp-win32-ia32",
      "version": "0.35.2",
      "integrity": "sha512-YYEhx9PImCC7T0tI8JDMi4DB9LwLCXCU5OWNYEXAxh5Q1ShKkyC6byxzoBJ3gEFDnH2lQckWuDe70G7mB2XJog==",
      "tarball": "https://registry.npmjs.org/@img/sharp-win32-ia32/-/sharp-win32-ia32-0.35.2.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "ia32"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-win32-x64@0.34.5": {
      "name": "@img/sharp-win32-x64",
      "version": "0.34.5",
      "integrity": "sha512-+29YMsqY2/9eFEiW93eqWnuLcWcufowXewwSNIT6UwZdUUCrM3oFjMWH/Z6/TMmb4hlFenmfAVbpWeup2jryCw==",
      "tarball": "https://registry.npmjs.org/@img/sharp-win32-x64/-/sharp-win32-x64-0.34.5.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@img/sharp-win32-x64@0.35.2": {
      "name": "@img/sharp-win32-x64",
      "version": "0.35.2",
      "integrity": "sha512-imoOyBcoM/iiUr4J6VPpCNjPnjvP/Gks95898yB8YqoGGYmHYbOyCuNv9FMhFgtaiHFGbHW8bxKqRV6VjtXThQ==",
      "tarball": "https://registry.npmjs.org/@img/sharp-win32-x64/-/sharp-win32-x64-0.35.2.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty-darwin-arm64@1.2.0-beta.15": {
      "name": "@lydell/node-pty-darwin-arm64",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-6TSBbzdcLiNTHl1mTuzflqXrkmcC36USVGvERoDgvHk2ItEDaMaFZuAJ1CqPmwYj0DyhCS16TVS8OGK9xZnjyQ==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty-darwin-arm64/-/node-pty-darwin-arm64-1.2.0-beta.15.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty-darwin-x64@1.2.0-beta.15": {
      "name": "@lydell/node-pty-darwin-x64",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-yDT2oqPqYMBScyuk1U9Rg5VKcrbMOD9o9jWYYamDADA3NSbUISroPChrqYRQ74Y7BQtNH4gqYAiWOZRi5uQZ0Q==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty-darwin-x64/-/node-pty-darwin-x64-1.2.0-beta.15.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty-linux-arm64@1.2.0-beta.15": {
      "name": "@lydell/node-pty-linux-arm64",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-wkbNF7dYAmtJv+o2+iztVlNwnUB4B0uX0wh/UD+mwMcmE2gNMnW9GChXO7fEE5XJokD0vB5idiHpGegaN+G/sg==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty-linux-arm64/-/node-pty-linux-arm64-1.2.0-beta.15.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty-linux-x64@1.2.0-beta.15": {
      "name": "@lydell/node-pty-linux-x64",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-+U/5AVvHT6W+8OCYcnJgN0Qgc0ycO3TfD6aaFJHK+WHij797f8gsi5dV1HEO9l6YQmWCD+VL5gaLDhx3mxHwCA==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty-linux-x64/-/node-pty-linux-x64-1.2.0-beta.15.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty-win32-arm64@1.2.0-beta.15": {
      "name": "@lydell/node-pty-win32-arm64",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-pyAk91w7wnnKrD4mrHXtIXRfmzSWV5bEzvRhurXcMCtCc2TJ424ciUskIgWMhAPP6y3KyUnqElj+U6kY3iOt0A==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty-win32-arm64/-/node-pty-win32-arm64-1.2.0-beta.15.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty-win32-x64@1.2.0-beta.15": {
      "name": "@lydell/node-pty-win32-x64",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-2f8twEmDVxZ7drchAXjtevpmSPhFok0avAnzXro4t5gmz0xsPNKkoZvymwtuIS3xo7PzQqZOPQ/YzwEMb7oIzQ==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty-win32-x64/-/node-pty-win32-x64-1.2.0-beta.15.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@lydell/node-pty@1.2.0-beta.15": {
      "name": "@lydell/node-pty",
      "version": "1.2.0-beta.15",
      "integrity": "sha512-Br8wBxzbxFwdWgk9uQ+rdzE0xfoxOK4QuGH54swhRwc5IxP6H9Y1/bcyazRGvNUs6XkB5qNVkezuKSRxUwZe7A==",
      "tarball": "https://registry.npmjs.org/@lydell/node-pty/-/node-pty-1.2.0-beta.15.tgz",
      "dependencies": {},
      "optionalDependencies": {
        "@lydell/node-pty-darwin-arm64": "@lydell/node-pty-darwin-arm64@1.2.0-beta.15",
        "@lydell/node-pty-darwin-x64": "@lydell/node-pty-darwin-x64@1.2.0-beta.15",
        "@lydell/node-pty-linux-arm64": "@lydell/node-pty-linux-arm64@1.2.0-beta.15",
        "@lydell/node-pty-linux-x64": "@lydell/node-pty-linux-x64@1.2.0-beta.15",
        "@lydell/node-pty-win32-arm64": "@lydell/node-pty-win32-arm64@1.2.0-beta.15",
        "@lydell/node-pty-win32-x64": "@lydell/node-pty-win32-x64@1.2.0-beta.15"
      }
    },
    "@napi-rs/canvas-android-arm64@0.1.80": {
      "name": "@napi-rs/canvas-android-arm64",
      "version": "0.1.80",
      "integrity": "sha512-sk7xhN/MoXeuExlggf91pNziBxLPVUqF2CAVnB57KLG/pz7+U5TKG8eXdc3pm0d7Od0WreB6ZKLj37sX9muGOQ==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-android-arm64/-/canvas-android-arm64-0.1.80.tgz",
      "os": [
        "android"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-darwin-arm64@0.1.80": {
      "name": "@napi-rs/canvas-darwin-arm64",
      "version": "0.1.80",
      "integrity": "sha512-O64APRTXRUiAz0P8gErkfEr3lipLJgM6pjATwavZ22ebhjYl/SUbpgM0xcWPQBNMP1n29afAC/Us5PX1vg+JNQ==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-darwin-arm64/-/canvas-darwin-arm64-0.1.80.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "arm64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-darwin-x64@0.1.80": {
      "name": "@napi-rs/canvas-darwin-x64",
      "version": "0.1.80",
      "integrity": "sha512-FqqSU7qFce0Cp3pwnTjVkKjjOtxMqRe6lmINxpIZYaZNnVI0H5FtsaraZJ36SiTHNjZlUB69/HhxNDT1Aaa9vA==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-darwin-x64/-/canvas-darwin-x64-0.1.80.tgz",
      "os": [
        "darwin"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-linux-arm-gnueabihf@0.1.80": {
      "name": "@napi-rs/canvas-linux-arm-gnueabihf",
      "version": "0.1.80",
      "integrity": "sha512-eyWz0ddBDQc7/JbAtY4OtZ5SpK8tR4JsCYEZjCE3dI8pqoWUC8oMwYSBGCYfsx2w47cQgQCgMVRVTFiiO38hHQ==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-linux-arm-gnueabihf/-/canvas-linux-arm-gnueabihf-0.1.80.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-linux-arm64-gnu@0.1.80": {
      "name": "@napi-rs/canvas-linux-arm64-gnu",
      "version": "0.1.80",
      "integrity": "sha512-qwA63t8A86bnxhuA/GwOkK3jvb+XTQaTiVML0vAWoHyoZYTjNs7BzoOONDgTnNtr8/yHrq64XXzUoLqDzU+Uuw==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-linux-arm64-gnu/-/canvas-linux-arm64-gnu-0.1.80.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-linux-arm64-musl@0.1.80": {
      "name": "@napi-rs/canvas-linux-arm64-musl",
      "version": "0.1.80",
      "integrity": "sha512-1XbCOz/ymhj24lFaIXtWnwv/6eFHXDrjP0jYkc6iHQ9q8oXKzUX1Lc6bu+wuGiLhGh2GS/2JlfORC5ZcXimRcg==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-linux-arm64-musl/-/canvas-linux-arm64-musl-0.1.80.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "arm64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-linux-riscv64-gnu@0.1.80": {
      "name": "@napi-rs/canvas-linux-riscv64-gnu",
      "version": "0.1.80",
      "integrity": "sha512-XTzR125w5ZMs0lJcxRlS1K3P5RaZ9RmUsPtd1uGt+EfDyYMu4c6SEROYsxyatbbu/2+lPe7MPHOO/0a0x7L/gw==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-linux-riscv64-gnu/-/canvas-linux-riscv64-gnu-0.1.80.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "riscv64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-linux-x64-gnu@0.1.80": {
      "name": "@napi-rs/canvas-linux-x64-gnu",
      "version": "0.1.80",
      "integrity": "sha512-BeXAmhKg1kX3UCrJsYbdQd3hIMDH/K6HnP/pG2LuITaXhXBiNdh//TVVVVCBbJzVQaV5gK/4ZOCMrQW9mvuTqA==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-linux-x64-gnu/-/canvas-linux-x64-gnu-0.1.80.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "glibc"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-linux-x64-musl@0.1.80": {
      "name": "@napi-rs/canvas-linux-x64-musl",
      "version": "0.1.80",
      "integrity": "sha512-x0XvZWdHbkgdgucJsRxprX/4o4sEed7qo9rCQA9ugiS9qE2QvP0RIiEugtZhfLH3cyI+jIRFJHV4Fuz+1BHHMg==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-linux-x64-musl/-/canvas-linux-x64-musl-0.1.80.tgz",
      "os": [
        "linux"
      ],
      "cpu": [
        "x64"
      ],
      "libc": [
        "musl"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas-win32-x64-msvc@0.1.80": {
      "name": "@napi-rs/canvas-win32-x64-msvc",
      "version": "0.1.80",
      "integrity": "sha512-Z8jPsM6df5V8B1HrCHB05+bDiCxjE9QA//3YrkKIdVDEwn5RKaqOxCJDRJkl48cJbylcrJbW4HxZbTte8juuPg==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas-win32-x64-msvc/-/canvas-win32-x64-msvc-0.1.80.tgz",
      "os": [
        "win32"
      ],
      "cpu": [
        "x64"
      ],
      "dependencies": {},
      "optionalDependencies": {}
    },
    "@napi-rs/canvas@0.1.80": {
      "name": "@napi-rs/canvas",
      "version": "0.1.80",
      "integrity": "sha512-DxuT1ClnIPts1kQx8FBmkk4BQDTfI5kIzywAaMjQSXfNnra5UFU9PwurXrl+Je3bJ6BGsp/zmshVVFbCmyI+ww==",
      "tarball": "https://registry.npmjs.org/@napi-rs/canvas/-/canvas-0.1.80.tgz",
      "dependencies": {},
      "optionalDependencies": {
        "@napi-rs/canvas-android-arm64": "@napi-rs/canvas-android-arm64@0.1.80",
        "@napi-rs/canvas-darwin-arm64": "@napi-rs/canvas-darwin-arm64@0.1.80",
        "@napi-rs/canvas-darwin-x64": "@napi-rs/canvas-darwin-x64@0.1.80",
        "@napi-rs/canvas-linux-arm-gnueabihf": "@napi-rs/canvas-linux-arm-gnueabihf@0.1.80",
        "@napi-rs/canvas-linux-arm64-gnu": "@napi-rs/canvas-linux-arm64-gnu@0.1.80",
        "@napi-rs/canvas-linux-arm64-musl": "@napi-rs/canvas-linux-arm64-musl@0.1.80",
        "@napi-rs/canvas-linux-riscv64-gnu": "@napi-rs/canvas-linux-riscv64-gnu@0.1.80",
        "@napi-rs/canvas-linux-x64-gnu": "@napi-rs/canvas-linux-x64-gnu@0.1.80",
        "@napi-rs/canvas-linux-x64-musl": "@napi-rs/canvas-linux-x64-musl@0.1.80",
        "@napi-rs/canvas-win32-x64-msvc": "@napi-rs/canvas-win32-x64-msvc@0.1.80"
      }
    },
    "ansi-regex@5.0.1": {
      "name": "ansi-regex",
      "version": "5.0.1",
      "integrity": "sha512-quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==",
      "tarball": "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "cli-progress@3.12.0": {
      "name": "cli-progress",
      "version": "3.12.0",
      "integrity": "sha512-tRkV3HJ1ASwm19THiiLIXLO7Im7wlTuKnvkYaTkyoAPefqjNg7W7DHKUlGRxy9vxDvbyCYQkQozvptuMkGCg8A==",
      "tarball": "https://registry.npmjs.org/cli-progress/-/cli-progress-3.12.0.tgz",
      "dependencies": {
        "string-width": "string-width@4.2.3"
      },
      "optionalDependencies": {}
    },
    "detect-libc@2.1.2": {
      "name": "detect-libc",
      "version": "2.1.2",
      "integrity": "sha512-Btj2BOOO83o3WyH59e8MgXsxEQVcarkUOpEYrubB0urwnN10yQ364rsiByU11nZlqWYZm05i/of7io4mzihBtQ==",
      "tarball": "https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "emoji-regex@8.0.0": {
      "name": "emoji-regex",
      "version": "8.0.0",
      "integrity": "sha512-MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==",
      "tarball": "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "gearhash-jit@1.0.2": {
      "name": "gearhash-jit",
      "version": "1.0.2",
      "integrity": "sha512-UhzJL4KXSdqAKepy/tZwmi2Rcy0YMmtiC4DQS4SURCuIWdh8ECZtnXK2ePRMLigfB61hRKdLK/Vgg2bSw73izQ==",
      "tarball": "https://registry.npmjs.org/gearhash-jit/-/gearhash-jit-1.0.2.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "is-fullwidth-code-point@3.0.0": {
      "name": "is-fullwidth-code-point",
      "version": "3.0.0",
      "integrity": "sha512-zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==",
      "tarball": "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "onnxruntime-common@1.24.3": {
      "name": "onnxruntime-common",
      "version": "1.24.3",
      "integrity": "sha512-GeuPZO6U/LBJXvwdaqHbuUmoXiEdeCjWi/EG7Y1HNnDwJYuk6WUbNXpF6luSUY8yASul3cmUlLGrCCL1ZgVXqA==",
      "tarball": "https://registry.npmjs.org/onnxruntime-common/-/onnxruntime-common-1.24.3.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "onnxruntime-common@1.27.0": {
      "name": "onnxruntime-common",
      "version": "1.27.0",
      "integrity": "sha512-3KxL5wIVqa8Ex08jxSzncm9CMgw8CjOFyOQ7SxvG9o0cVLlhTNKXyIQuTbtX4tGPJEf73OER2xrjt4HJSBL4ow==",
      "tarball": "https://registry.npmjs.org/onnxruntime-common/-/onnxruntime-common-1.27.0.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "onnxruntime-node@1.24.3": {
      "name": "onnxruntime-node",
      "version": "1.24.3",
      "integrity": "sha512-JH7+czbc8ALA819vlTgcV+Q214/+VjGeBHDjX81+ZCD0PCVCIFGFNtT0V4sXG/1JXypKPgScQcB3ij/hk3YnTg==",
      "tarball": "https://registry.npmjs.org/onnxruntime-node/-/onnxruntime-node-1.24.3.tgz",
      "os": [
        "win32",
        "darwin",
        "linux"
      ],
      "dependencies": {
        "onnxruntime-common": "onnxruntime-common@1.24.3"
      },
      "optionalDependencies": {}
    },
    "onnxruntime-node@1.27.0": {
      "name": "onnxruntime-node",
      "version": "1.27.0",
      "integrity": "sha512-QEzGwrvNBgv4uPVdnbHsOGG4G6T96mdlcFI8aAKPjMU8wOPpVocPXb6k3QGkaZagVTv2G9Bnnbo6Z3JdXr1fQw==",
      "tarball": "https://registry.npmjs.org/onnxruntime-node/-/onnxruntime-node-1.27.0.tgz",
      "os": [
        "win32",
        "darwin",
        "linux"
      ],
      "dependencies": {
        "onnxruntime-common": "onnxruntime-common@1.27.0"
      },
      "optionalDependencies": {}
    },
    "pdf-parse@2.4.5": {
      "name": "pdf-parse",
      "version": "2.4.5",
      "integrity": "sha512-mHU89HGh7v+4u2ubfnevJ03lmPgQ5WU4CxAVmTSh/sxVTEDYd1er/dKS/A6vg77NX47KTEoihq8jZBLr8Cxuwg==",
      "tarball": "https://registry.npmjs.org/pdf-parse/-/pdf-parse-2.4.5.tgz",
      "dependencies": {
        "@napi-rs/canvas": "@napi-rs/canvas@0.1.80",
        "pdfjs-dist": "pdfjs-dist@5.4.296"
      },
      "optionalDependencies": {}
    },
    "pdfjs-dist@5.4.296": {
      "name": "pdfjs-dist",
      "version": "5.4.296",
      "integrity": "sha512-DlOzet0HO7OEnmUmB6wWGJrrdvbyJKftI1bhMitK7O2N8W2gc757yyYBbINy9IDafXAV9wmKr9t7xsTaNKRG5Q==",
      "tarball": "https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-5.4.296.tgz",
      "dependencies": {},
      "optionalDependencies": {
        "@napi-rs/canvas": "@napi-rs/canvas@0.1.80"
      }
    },
    "playwright-core@1.63.0": {
      "name": "playwright-core",
      "version": "1.63.0",
      "integrity": "sha512-rYCsBF/M5HjUch52bbtVONEFjv6Xu8sm8h72dNlR5bzIE1fvC/bxgspzkjSfU+MweEMmPM8KJebG6nnyxo5mCg==",
      "tarball": "https://registry.npmjs.org/playwright-core/-/playwright-core-1.63.0.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "semver@7.8.5": {
      "name": "semver",
      "version": "7.8.5",
      "integrity": "sha512-Y7/KDsb8LjooZpwaqGyulO6DQlksgCncchHGk+sZIY4SBvUocMBEFH5Ur1fI4dV+Jvl0w6cjvucaIi40puRioA==",
      "tarball": "https://registry.npmjs.org/semver/-/semver-7.8.5.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    },
    "sharp@0.34.5": {
      "name": "sharp",
      "version": "0.34.5",
      "integrity": "sha512-Ou9I5Ft9WNcCbXrU9cMgPBcCK8LiwLqcbywW3t4oDV37n1pzpuNLsYiAV8eODnjbtQlSDwZ2cUEeQz4E54Hltg==",
      "tarball": "https://registry.npmjs.org/sharp/-/sharp-0.34.5.tgz",
      "dependencies": {
        "@img/colour": "@img/colour@1.1.0",
        "detect-libc": "detect-libc@2.1.2",
        "semver": "semver@7.8.5"
      },
      "optionalDependencies": {
        "@img/sharp-darwin-arm64": "@img/sharp-darwin-arm64@0.34.5",
        "@img/sharp-darwin-x64": "@img/sharp-darwin-x64@0.34.5",
        "@img/sharp-libvips-darwin-arm64": "@img/sharp-libvips-darwin-arm64@1.2.4",
        "@img/sharp-libvips-darwin-x64": "@img/sharp-libvips-darwin-x64@1.2.4",
        "@img/sharp-libvips-linux-arm": "@img/sharp-libvips-linux-arm@1.2.4",
        "@img/sharp-libvips-linux-arm64": "@img/sharp-libvips-linux-arm64@1.2.4",
        "@img/sharp-libvips-linux-ppc64": "@img/sharp-libvips-linux-ppc64@1.2.4",
        "@img/sharp-libvips-linux-riscv64": "@img/sharp-libvips-linux-riscv64@1.2.4",
        "@img/sharp-libvips-linux-s390x": "@img/sharp-libvips-linux-s390x@1.2.4",
        "@img/sharp-libvips-linux-x64": "@img/sharp-libvips-linux-x64@1.2.4",
        "@img/sharp-libvips-linuxmusl-arm64": "@img/sharp-libvips-linuxmusl-arm64@1.2.4",
        "@img/sharp-libvips-linuxmusl-x64": "@img/sharp-libvips-linuxmusl-x64@1.2.4",
        "@img/sharp-linux-arm": "@img/sharp-linux-arm@0.34.5",
        "@img/sharp-linux-arm64": "@img/sharp-linux-arm64@0.34.5",
        "@img/sharp-linux-ppc64": "@img/sharp-linux-ppc64@0.34.5",
        "@img/sharp-linux-riscv64": "@img/sharp-linux-riscv64@0.34.5",
        "@img/sharp-linux-s390x": "@img/sharp-linux-s390x@0.34.5",
        "@img/sharp-linux-x64": "@img/sharp-linux-x64@0.34.5",
        "@img/sharp-linuxmusl-arm64": "@img/sharp-linuxmusl-arm64@0.34.5",
        "@img/sharp-linuxmusl-x64": "@img/sharp-linuxmusl-x64@0.34.5",
        "@img/sharp-wasm32": "@img/sharp-wasm32@0.34.5",
        "@img/sharp-win32-arm64": "@img/sharp-win32-arm64@0.34.5",
        "@img/sharp-win32-ia32": "@img/sharp-win32-ia32@0.34.5",
        "@img/sharp-win32-x64": "@img/sharp-win32-x64@0.34.5"
      }
    },
    "sharp@0.35.2": {
      "name": "sharp",
      "version": "0.35.2",
      "integrity": "sha512-FVtFjtBCMiJS6yb5CX7Sop45WFMpeGw6oRKuJnXYgf/f1ms/D7LE/ZUSNxnW7rZ/dbslQWYkoqFHGPaDBtaK4w==",
      "tarball": "https://registry.npmjs.org/sharp/-/sharp-0.35.2.tgz",
      "dependencies": {
        "@img/colour": "@img/colour@1.1.0",
        "detect-libc": "detect-libc@2.1.2",
        "semver": "semver@7.8.5"
      },
      "optionalDependencies": {
        "@img/sharp-darwin-arm64": "@img/sharp-darwin-arm64@0.35.2",
        "@img/sharp-darwin-x64": "@img/sharp-darwin-x64@0.35.2",
        "@img/sharp-freebsd-wasm32": "@img/sharp-freebsd-wasm32@0.35.2",
        "@img/sharp-libvips-darwin-arm64": "@img/sharp-libvips-darwin-arm64@1.3.1",
        "@img/sharp-libvips-darwin-x64": "@img/sharp-libvips-darwin-x64@1.3.1",
        "@img/sharp-libvips-linux-arm": "@img/sharp-libvips-linux-arm@1.3.1",
        "@img/sharp-libvips-linux-arm64": "@img/sharp-libvips-linux-arm64@1.3.1",
        "@img/sharp-libvips-linux-ppc64": "@img/sharp-libvips-linux-ppc64@1.3.1",
        "@img/sharp-libvips-linux-riscv64": "@img/sharp-libvips-linux-riscv64@1.3.1",
        "@img/sharp-libvips-linux-s390x": "@img/sharp-libvips-linux-s390x@1.3.1",
        "@img/sharp-libvips-linux-x64": "@img/sharp-libvips-linux-x64@1.3.1",
        "@img/sharp-libvips-linuxmusl-arm64": "@img/sharp-libvips-linuxmusl-arm64@1.3.1",
        "@img/sharp-libvips-linuxmusl-x64": "@img/sharp-libvips-linuxmusl-x64@1.3.1",
        "@img/sharp-linux-arm": "@img/sharp-linux-arm@0.35.2",
        "@img/sharp-linux-arm64": "@img/sharp-linux-arm64@0.35.2",
        "@img/sharp-linux-ppc64": "@img/sharp-linux-ppc64@0.35.2",
        "@img/sharp-linux-riscv64": "@img/sharp-linux-riscv64@0.35.2",
        "@img/sharp-linux-s390x": "@img/sharp-linux-s390x@0.35.2",
        "@img/sharp-linux-x64": "@img/sharp-linux-x64@0.35.2",
        "@img/sharp-linuxmusl-arm64": "@img/sharp-linuxmusl-arm64@0.35.2",
        "@img/sharp-linuxmusl-x64": "@img/sharp-linuxmusl-x64@0.35.2",
        "@img/sharp-webcontainers-wasm32": "@img/sharp-webcontainers-wasm32@0.35.2",
        "@img/sharp-win32-arm64": "@img/sharp-win32-arm64@0.35.2",
        "@img/sharp-win32-ia32": "@img/sharp-win32-ia32@0.35.2",
        "@img/sharp-win32-x64": "@img/sharp-win32-x64@0.35.2"
      }
    },
    "string-width@4.2.3": {
      "name": "string-width",
      "version": "4.2.3",
      "integrity": "sha512-wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==",
      "tarball": "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz",
      "dependencies": {
        "emoji-regex": "emoji-regex@8.0.0",
        "is-fullwidth-code-point": "is-fullwidth-code-point@3.0.0",
        "strip-ansi": "strip-ansi@6.0.1"
      },
      "optionalDependencies": {}
    },
    "strip-ansi@6.0.1": {
      "name": "strip-ansi",
      "version": "6.0.1",
      "integrity": "sha512-Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==",
      "tarball": "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz",
      "dependencies": {
        "ansi-regex": "ansi-regex@5.0.1"
      },
      "optionalDependencies": {}
    },
    "tslib@2.8.1": {
      "name": "tslib",
      "version": "2.8.1",
      "integrity": "sha512-oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==",
      "tarball": "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz",
      "dependencies": {},
      "optionalDependencies": {}
    }
  }
} as const;
